import fs from "fs";
import path from "path";
import { validateIdentityGraph, type IdentityGraph } from "./identity-types";
const root = path.resolve(__dirname, "..");
const graph: IdentityGraph = JSON.parse(fs.readFileSync(path.join(root, "data/identity/catalog.json"), "utf8"));
validateIdentityGraph(graph, JSON.parse(fs.readFileSync(path.join(root, "data/compact.json"), "utf8")));
fs.writeFileSync(path.join(root, "src/identity-data.ts"),
  '// Generated by scripts/build-identities.ts. Do not edit.\nimport type { IdentityGraph } from "./identity";\nconst graph: IdentityGraph = ' + JSON.stringify(graph) + ';\nexport default graph;\n');
console.log(`Validated ${graph.identities.length} identities, ${graph.catalogLinks.length} catalog links`);
