/**
 * Reviewed mapping from Brazil's RENAVAM make/model registrations to catalog
 * makes and model families, used by scripts/import-senatran-br.ts.
 *
 * RENAVAM records each vehicle's make and model as one abbreviated string,
 * often down to the trim ("CHEV/ONIX 10MT LT2", "I/TOYOTA HILUX CDSRXA4FD"),
 * and does not record a vehicle type. Rather than guess model names from those
 * strings, the importer keeps only the families listed here, which cover about
 * 91% of the vehicles manufactured since 1990. The importer logs the largest
 * unmapped families so this table can grow; add a row only when the family is
 * a real marketed model, using the catalog's existing spelling where the model
 * is already listed.
 *
 * Heavy trucks and bus bodies (numeric codes such as "VW/24.280 CRM 6X2",
 * coachbuilders such as "M.BENZ/MPOLO TORINO U") and trailers are not mapped.
 */

/** RENAVAM make codes, as they prefix "MAKE/MODEL", to catalog make names. */
export const RENAVAM_MAKES: Record<string, string> = {
  AUDI: "AUDI",
  BAJAJ: "BAJAJ",
  BMW: "BMW",
  BYD: "BYD",
  CAOACHERY: "CHERY",
  CHERY: "CHERY",
  CHEV: "CHEVROLET",
  CHEVROLET: "CHEVROLET",
  CITROEN: "CITROEN",
  DAFRA: "DAFRA",
  DODGE: "DODGE",
  FIAT: "FIAT",
  FORD: "FORD",
  GEELY: "GEELY",
  GM: "CHEVROLET",
  GWM: "GWM",
  HONDA: "HONDA",
  HYUNDAI: "HYUNDAI",
  IVECO: "IVECO",
  JAC: "JAC",
  JAECOO: "JAECOO",
  JEEP: "JEEP",
  "JTA-SUZUKI": "SUZUKI",
  KASINSKI: "KASINSKI",
  KAWASAKI: "KAWASAKI",
  KIA: "KIA",
  "L.ROVER": "LAND ROVER",
  "LAND ROVER": "LAND ROVER",
  LIFAN: "LIFAN",
  LR: "LAND ROVER",
  LROVER: "LAND ROVER",
  MARCOPOLO: "MARCOPOLO",
  MINI: "MINI",
  MITSUBISHI: "MITSUBISHI",
  MMC: "MITSUBISHI",
  MOTTU: "MOTTU",
  MPOLO: "MARCOPOLO",
  NISSAN: "NISSAN",
  OMODA: "OMODA",
  PEUGEOT: "PEUGEOT",
  PORSCHE: "PORSCHE",
  RAM: "RAM",
  RE: "ROYAL ENFIELD",
  RENAULT: "RENAULT",
  "ROYAL ENFIELD": "ROYAL ENFIELD",
  SHINERAY: "SHINERAY",
  SUBARU: "SUBARU",
  SUNDOWN: "SUNDOWN",
  SUZUKI: "SUZUKI",
  TOYOTA: "TOYOTA",
  TRIUMPH: "TRIUMPH",
  TROLLER: "TROLLER",
  VOLKS: "VOLKSWAGEN",
  VOLKSWAGEN: "VOLKSWAGEN",
  VOLVO: "VOLVO",
  VW: "VOLKSWAGEN",
  YAMAHA: "YAMAHA",
};

/**
 * [catalog make, model family, vehicle type, RENAVAM model prefixes]. Without
 * prefixes the family name is the prefix. A prefix matches a registered model
 * that starts with it when the next character is not a letter, so "CG" covers
 * "CG 160 FAN" and "CG150 TITAN"; a trailing "*" matches any continuation.
 * The longest matching prefix wins. Vehicle types: 1 Motorcycle, 2 Passenger
 * Car, 3 Truck (pickups and vans), 5 Bus, 7 MPV (SUVs and minivans).
 */
export const RENAVAM_MODELS: [string, string, number, string[]?][] = [
  // Honda motorcycles
  ["HONDA", "CG", 1],
  ["HONDA", "BIZ", 1, ["BIZ", "C100 BIZ"]],
  ["HONDA", "DREAM", 1, ["C100 DREAM"]],
  ["HONDA", "POP", 1],
  ["HONDA", "BROS", 1, ["NXR"]],
  ["HONDA", "XRE", 1],
  ["HONDA", "CB", 1],
  ["HONDA", "CBX", 1],
  ["HONDA", "CBR", 1],
  ["HONDA", "PCX", 1],
  ["HONDA", "ELITE", 1],
  ["HONDA", "LEAD", 1],
  ["HONDA", "NX", 1],
  ["HONDA", "XR", 1],
  ["HONDA", "XLR", 1],
  ["HONDA", "XL", 1],
  ["HONDA", "XLX", 1],
  ["HONDA", "NC", 1],
  ["HONDA", "SH", 1],
  ["HONDA", "ADV", 1],
  ["HONDA", "SHADOW", 1, ["SHADOW", "VT600C"]],
  ["HONDA", "CRF", 1],
  // Honda cars
  ["HONDA", "CIVIC", 2],
  ["HONDA", "FIT", 2],
  ["HONDA", "CITY", 2],
  ["HONDA", "ACCORD", 2],
  ["HONDA", "HR-V", 7],
  ["HONDA", "WR-V", 7],
  ["HONDA", "CR-V", 7, ["CR-V", "CRV"]],
  ["HONDA", "ZR-V", 7],
  // Volkswagen
  ["VOLKSWAGEN", "GOL", 2],
  ["VOLKSWAGEN", "FOX", 2],
  ["VOLKSWAGEN", "CROSSFOX", 2],
  ["VOLKSWAGEN", "SPACEFOX", 2],
  ["VOLKSWAGEN", "SPACECROSS", 2],
  ["VOLKSWAGEN", "SAVEIRO", 3],
  ["VOLKSWAGEN", "POLO", 2],
  ["VOLKSWAGEN", "POLO SEDAN", 2],
  ["VOLKSWAGEN", "POLO TRACK", 2],
  ["VOLKSWAGEN", "VOYAGE", 2],
  ["VOLKSWAGEN", "KOMBI", 3],
  ["VOLKSWAGEN", "PARATI", 2],
  ["VOLKSWAGEN", "T-CROSS", 7, ["T CROSS"]],
  ["VOLKSWAGEN", "GOLF", 2],
  ["VOLKSWAGEN", "SANTANA", 2],
  ["VOLKSWAGEN", "QUANTUM", 2],
  ["VOLKSWAGEN", "NIVUS", 7],
  ["VOLKSWAGEN", "VIRTUS", 2],
  ["VOLKSWAGEN", "UP", 2],
  ["VOLKSWAGEN", "AMAROK", 3],
  ["VOLKSWAGEN", "JETTA", 2],
  ["VOLKSWAGEN", "LOGUS", 2],
  ["VOLKSWAGEN", "POINTER", 2],
  ["VOLKSWAGEN", "APOLLO", 2],
  ["VOLKSWAGEN", "FUSCA", 2],
  ["VOLKSWAGEN", "TERA", 7],
  ["VOLKSWAGEN", "TAOS", 7],
  ["VOLKSWAGEN", "TIGUAN", 7],
  ["VOLKSWAGEN", "PASSAT", 2],
  ["VOLKSWAGEN", "BORA", 2],
  ["VOLKSWAGEN", "BEETLE", 2],
  ["VOLKSWAGEN", "DELIVERY", 3],
  // Fiat
  ["FIAT", "UNO", 2],
  ["FIAT", "PALIO", 2],
  ["FIAT", "PALIO WEEKEND", 2, ["PALIO WEEKEND", "WEEKEND"]],
  ["FIAT", "SIENA", 2],
  ["FIAT", "STRADA", 3],
  ["FIAT", "ARGO", 2],
  ["FIAT", "MOBI", 2],
  ["FIAT", "TORO", 3],
  ["FIAT", "FIORINO", 3],
  ["FIAT", "PUNTO", 2],
  ["FIAT", "CRONOS", 2],
  ["FIAT", "IDEA", 7],
  ["FIAT", "PULSE", 7],
  ["FIAT", "FASTBACK", 7],
  ["FIAT", "TEMPRA", 2],
  ["FIAT", "DOBLO", 7],
  ["FIAT", "TIPO", 2],
  ["FIAT", "DUCATO", 3],
  ["FIAT", "STILO", 2],
  ["FIAT", "MAREA", 2],
  ["FIAT", "MAREA WEEKEND", 2],
  ["FIAT", "LINEA", 2],
  ["FIAT", "ELBA", 2],
  ["FIAT", "PREMIO", 2],
  ["FIAT", "BRAVO", 2],
  ["FIAT", "BRAVA", 2],
  ["FIAT", "500", 2],
  ["FIAT", "FREEMONT", 7],
  ["FIAT", "TITANO", 3],
  ["FIAT", "SCUDO", 3],
  // Chevrolet
  ["CHEVROLET", "ONIX", 2],
  ["CHEVROLET", "ONIX PLUS", 2],
  ["CHEVROLET", "CORSA", 2],
  ["CHEVROLET", "CORSA CLASSIC", 2],
  ["CHEVROLET", "CELTA", 2],
  ["CHEVROLET", "CLASSIC", 2],
  ["CHEVROLET", "S10", 3],
  ["CHEVROLET", "PRISMA", 2],
  ["CHEVROLET", "VECTRA", 2],
  ["CHEVROLET", "MONTANA", 3],
  ["CHEVROLET", "ASTRA", 2],
  ["CHEVROLET", "TRACKER", 7],
  ["CHEVROLET", "KADETT", 2],
  ["CHEVROLET", "SPIN", 7],
  ["CHEVROLET", "MONZA", 2],
  ["CHEVROLET", "CRUZE", 2],
  ["CHEVROLET", "COBALT", 2],
  ["CHEVROLET", "AGILE", 2],
  ["CHEVROLET", "MERIVA", 7],
  ["CHEVROLET", "ZAFIRA", 7],
  ["CHEVROLET", "CHEVETTE", 2],
  ["CHEVROLET", "BLAZER", 7],
  ["CHEVROLET", "OMEGA", 2],
  ["CHEVROLET", "D20", 3, ["D20", "CHEVROLET D20"]],
  ["CHEVROLET", "C20", 3, ["C20", "CHEVROLET C20"]],
  ["CHEVROLET", "CAPTIVA", 7],
  ["CHEVROLET", "SONIC", 2],
  ["CHEVROLET", "TRAILBLAZER", 7],
  ["CHEVROLET", "SILVERADO", 3],
  ["CHEVROLET", "EQUINOX", 7],
  ["CHEVROLET", "CHEVY", 3],
  ["CHEVROLET", "OPALA", 2],
  ["CHEVROLET", "CARAVAN", 2],
  ["CHEVROLET", "SPARK EUV", 7],
  ["CHEVROLET", "CAMARO", 2],
  // Ford
  ["FORD", "FIESTA", 2],
  ["FORD", "KA", 2],
  ["FORD", "ECOSPORT", 7],
  ["FORD", "ESCORT", 2],
  ["FORD", "RANGER", 3],
  ["FORD", "FOCUS", 2],
  ["FORD", "PAMPA", 3],
  ["FORD", "COURIER", 3],
  ["FORD", "VERONA", 2],
  ["FORD", "FUSION", 2],
  ["FORD", "F-1000", 3, ["F1000"]],
  ["FORD", "F-4000", 3, ["F4000", "F 4000"]],
  ["FORD", "VERSAILLES", 2],
  ["FORD", "F-250", 3, ["F250", "F-250", "F 250"]],
  ["FORD", "F-350", 3, ["F350", "F-350", "F 350"]],
  ["FORD", "F-150", 3, ["F150", "F-150", "F 150"]],
  ["FORD", "MONDEO", 2],
  ["FORD", "TERRITORY", 7],
  ["FORD", "TRANSIT", 3],
  ["FORD", "DEL REY", 2],
  ["FORD", "ROYALE", 2],
  ["FORD", "EDGE", 7],
  ["FORD", "MAVERICK", 3],
  ["FORD", "BRONCO SPORT", 7, ["BRONCO S"]],
  ["FORD", "MUSTANG", 2],
  // Yamaha
  ["YAMAHA", "YBR", 1],
  ["YAMAHA", "FACTOR", 1, ["FACTOR", "YBR150", "YBR125", "YBR125I"]],
  ["YAMAHA", "FAZER", 1, ["FAZER", "FZ25", "FZ15", "YS150"]],
  ["YAMAHA", "XTZ", 1],
  ["YAMAHA", "LANDER", 1, ["LANDER", "XTZ250 LANDER", "XTZ 250 LANDER"]],
  ["YAMAHA", "TENERE", 1, ["XTZ250 TENERE"]],
  ["YAMAHA", "CROSSER", 1, ["CROSSER", "XTZ150 CROSSER"]],
  ["YAMAHA", "NEO", 1],
  ["YAMAHA", "NMAX", 1],
  ["YAMAHA", "XMAX", 1],
  ["YAMAHA", "FLUO", 1],
  ["YAMAHA", "CRYPTON", 1, ["CRYPTON", "T115 CRYPTON"]],
  ["YAMAHA", "MT-03", 1, ["MT03", "MT-03"]],
  ["YAMAHA", "MT-07", 1, ["MT07"]],
  ["YAMAHA", "MT-09", 1, ["MT09"]],
  ["YAMAHA", "YZF", 1],
  ["YAMAHA", "XT", 1],
  ["YAMAHA", "RD", 1],
  ["YAMAHA", "DT", 1],
  ["YAMAHA", "XJ6", 1],
  ["YAMAHA", "VIRAGO", 1],
  ["YAMAHA", "AEROX", 1],
  ["YAMAHA", "TDM", 1],
  ["YAMAHA", "DRAG STAR", 1],
  // Renault
  ["RENAULT", "SANDERO", 2],
  ["RENAULT", "KWID", 2],
  ["RENAULT", "E-KWID", 2],
  ["RENAULT", "CLIO", 2],
  ["RENAULT", "LOGAN", 2],
  ["RENAULT", "DUSTER", 7],
  ["RENAULT", "MASTER", 3],
  ["RENAULT", "OROCH", 3],
  ["RENAULT", "SCENIC", 7],
  ["RENAULT", "CAPTUR", 7],
  ["RENAULT", "FLUENCE", 2],
  ["RENAULT", "KARDIAN", 7],
  ["RENAULT", "MEGANE", 2, ["MEGANE", "MEGANEGT", "MEGANESD"]],
  ["RENAULT", "KANGOO", 3, ["KANGOO", "KGOO"]],
  ["RENAULT", "SYMBOL", 2],
  ["RENAULT", "19", 2],
  ["RENAULT", "TWINGO", 2],
  ["RENAULT", "BOREAL", 7],
  // Toyota
  ["TOYOTA", "COROLLA", 2],
  ["TOYOTA", "COROLLA CROSS", 7, ["CCROSS", "COROLLA CROSS"]],
  ["TOYOTA", "HILUX", 3],
  ["TOYOTA", "HILUX SW4", 7, ["HILUXSW4", "HILUX SW*"]],
  ["TOYOTA", "ETIOS", 2],
  ["TOYOTA", "YARIS", 2],
  ["TOYOTA", "YARIS CROSS", 7, ["YCROSS"]],
  ["TOYOTA", "RAV4", 7, ["RAV4", "RAV4H", "RAV 4"]],
  ["TOYOTA", "FIELDER", 2],
  ["TOYOTA", "BANDEIRANTE", 3, ["BANDEIRANTE", "BAND.", "BAND"]],
  ["TOYOTA", "CAMRY", 2],
  ["TOYOTA", "PRIUS", 2],
  // Hyundai
  ["HYUNDAI", "HB20", 2],
  ["HYUNDAI", "HB20S", 2],
  ["HYUNDAI", "HB20X", 2],
  ["HYUNDAI", "CRETA", 7],
  ["HYUNDAI", "TUCSON", 7],
  ["HYUNDAI", "I30", 2],
  ["HYUNDAI", "HR", 3],
  ["HYUNDAI", "IX35", 7],
  ["HYUNDAI", "SANTA FE", 7, ["SANTA FE", "SANTAFE"]],
  ["HYUNDAI", "AZERA", 2],
  ["HYUNDAI", "ELANTRA", 2],
  ["HYUNDAI", "H100", 3],
  ["HYUNDAI", "VELOSTER", 2],
  ["HYUNDAI", "VERACRUZ", 7],
  ["HYUNDAI", "SONATA", 2],
  // Jeep
  ["JEEP", "RENEGADE", 7],
  ["JEEP", "COMPASS", 7],
  ["JEEP", "COMMANDER", 7],
  ["JEEP", "GRAND CHEROKEE", 7, ["GCHEROKEE", "G.CHEROKEE", "GRAND CHEROKEE"]],
  ["JEEP", "CHEROKEE", 7],
  ["JEEP", "WRANGLER", 7],
  // Nissan
  ["NISSAN", "KICKS", 7],
  ["NISSAN", "VERSA", 2],
  ["NISSAN", "FRONTIER", 3],
  ["NISSAN", "MARCH", 2],
  ["NISSAN", "SENTRA", 2],
  ["NISSAN", "LIVINA", 7],
  ["NISSAN", "GRAND LIVINA", 7],
  ["NISSAN", "TIIDA", 2],
  ["NISSAN", "KAIT", 7],
  ["NISSAN", "V-DRIVE", 2],
  // Peugeot
  ["PEUGEOT", "206", 2],
  ["PEUGEOT", "207", 2, ["207", "207HB"]],
  ["PEUGEOT", "207 PASSION", 2, ["207PASSION", "207 PASSION"]],
  ["PEUGEOT", "207 SW", 2, ["207SW", "207 SW"]],
  ["PEUGEOT", "208", 2],
  ["PEUGEOT", "2008", 7],
  ["PEUGEOT", "307", 2, ["307", "307HB"]],
  ["PEUGEOT", "307 SEDAN", 2, ["307SD"]],
  ["PEUGEOT", "307 SW", 2, ["307SW", "307 SW"]],
  ["PEUGEOT", "308", 2],
  ["PEUGEOT", "408", 2],
  ["PEUGEOT", "306", 2],
  ["PEUGEOT", "106", 2],
  ["PEUGEOT", "3008", 7],
  ["PEUGEOT", "BOXER", 3],
  ["PEUGEOT", "EXPERT", 3],
  ["PEUGEOT", "PARTNER", 3, ["PARTNER", "PARTRAPID"]],
  ["PEUGEOT", "HOGGAR", 3],
  ["PEUGEOT", "504", 2],
  ["PEUGEOT", "405", 2],
  // Citroen
  ["CITROEN", "C3", 2],
  ["CITROEN", "C3 AIRCROSS", 7, ["C3AIRCROSS", "C3 AIRCROSS", "AIRCROSS"]],
  ["CITROEN", "C3 PICASSO", 7],
  ["CITROEN", "C4", 2],
  ["CITROEN", "C4 LOUNGE", 2, ["C4L"]],
  ["CITROEN", "C4 PICASSO", 7, ["C4PIC", "C4 PIC"]],
  ["CITROEN", "C4 PALLAS", 2],
  ["CITROEN", "C4 CACTUS", 7, ["C4CACTUS", "C4 CACTUS"]],
  ["CITROEN", "XSARA", 2],
  ["CITROEN", "XSARA PICASSO", 7, ["XSARA PICASSO*", "PICASSO"]],
  ["CITROEN", "BASALT", 7],
  ["CITROEN", "JUMPER", 3],
  ["CITROEN", "JUMPY", 3],
  ["CITROEN", "C5", 2],
  // Mitsubishi
  ["MITSUBISHI", "L200", 3],
  ["MITSUBISHI", "L200 TRITON", 3],
  ["MITSUBISHI", "TRITON", 3],
  ["MITSUBISHI", "PAJERO", 7],
  ["MITSUBISHI", "PAJERO TR4", 7],
  ["MITSUBISHI", "PAJERO SPORT", 7],
  ["MITSUBISHI", "PAJERO DAKAR", 7],
  ["MITSUBISHI", "ASX", 7],
  ["MITSUBISHI", "OUTLANDER", 7],
  ["MITSUBISHI", "ECLIPSE CROSS", 7, ["ECLIPSE CR", "ECLIPSE CROSS"]],
  ["MITSUBISHI", "LANCER", 2],
  // Suzuki
  ["SUZUKI", "EN125", 1],
  ["SUZUKI", "INTRUDER", 1],
  ["SUZUKI", "BURGMAN", 1, ["BURGMAN", "AN125"]],
  ["SUZUKI", "KATANA", 1],
  ["SUZUKI", "BANDIT", 1],
  ["SUZUKI", "GSR", 1],
  ["SUZUKI", "V-STROM", 1, ["V-STROM", "VSTROM", "DL"]],
  ["SUZUKI", "BOULEVARD", 1, ["BOULEVARD", "BOULEV"]],
  ["SUZUKI", "GSX-R", 1, ["GSXR", "GSX-R"]],
  ["SUZUKI", "GSX", 1],
  ["SUZUKI", "JIMNY", 7],
  ["SUZUKI", "GRAND VITARA", 7, ["G.VITARA", "GVITARA", "GRAND VITARA"]],
  ["SUZUKI", "VITARA", 7],
  // Kia
  ["KIA", "SPORTAGE", 7],
  ["KIA", "CERATO", 2],
  ["KIA", "BESTA", 3],
  ["KIA", "BONGO", 3, ["UK2500", "K2500", "K2700", "BONGO"]],
  ["KIA", "PICANTO", 2],
  ["KIA", "SORENTO", 7],
  ["KIA", "SOUL", 2],
  // Chery (Caoa Chery)
  ["CHERY", "TIGGO", 7],
  ["CHERY", "TIGGO 2", 7, ["TIGGO2", "TIGGO 2 *"]],
  ["CHERY", "TIGGO 3X", 7, ["TIGGO3X"]],
  ["CHERY", "TIGGO 5X", 7, ["TIGGO5X", "TIGGO 5X"]],
  ["CHERY", "TIGGO 7", 7, ["TIGGO7"]],
  ["CHERY", "TIGGO 8", 7, ["TIGGO8"]],
  ["CHERY", "QQ", 2, ["QQ", "QQ3"]],
  ["CHERY", "FACE", 2],
  ["CHERY", "CELER", 2],
  ["CHERY", "ARRIZO 6", 2, ["ARRIZO6"]],
  // BYD
  ["BYD", "DOLPHIN", 2],
  ["BYD", "DOLPHIN MINI", 2],
  ["BYD", "SONG PLUS", 7],
  ["BYD", "SONG PRO", 7],
  ["BYD", "KING", 2],
  ["BYD", "YUAN PLUS", 7],
  ["BYD", "YUAN PRO", 7],
  ["BYD", "SEAL", 2],
  // GWM
  ["GWM", "HAVAL H6", 7],
  ["GWM", "HAVAL H9", 7],
  ["GWM", "ORA 03", 2],
  ["GWM", "TANK 300", 7],
  ["GWM", "POER", 3],
  // BMW cars and motorcycles
  ["BMW", "320I", 2],
  ["BMW", "328I", 2],
  ["BMW", "X1", 7],
  ["BMW", "X3", 7],
  ["BMW", "X4", 7],
  ["BMW", "X5", 7],
  ["BMW", "X6", 7],
  ["BMW", "G 310 GS", 1, ["G310 GS"]],
  ["BMW", "G 310 R", 1, ["G310 R"]],
  ["BMW", "R 1250 GS", 1, ["R1250GS"]],
  ["BMW", "R 1300 GS", 1, ["R1300GS"]],
  ["BMW", "R 1200 GS", 1, ["R1200 GS"]],
  ["BMW", "F 800 GS", 1, ["F800 GS", "F 800 GS"]],
  ["BMW", "F 850 GS", 1, ["F850 GS", "F850GS"]],
  ["BMW", "S 1000 RR", 1, ["S1000 RR", "S 1000 RR", "S1000RR"]],
  // Audi
  ["AUDI", "A3", 2],
  ["AUDI", "A4", 2],
  ["AUDI", "A5", 2],
  ["AUDI", "Q3", 7],
  ["AUDI", "Q5", 7],
  // Volvo cars
  ["VOLVO", "XC60", 7],
  ["VOLVO", "XC40", 7],
  ["VOLVO", "XC90", 7],
  ["VOLVO", "EX30", 7],
  // Ram
  ["RAM", "RAMPAGE", 3],
  ["RAM", "1500", 3],
  ["RAM", "2500", 3],
  ["RAM", "3500", 3],
  // Land Rover
  ["LAND ROVER", "EVOQUE", 7],
  ["LAND ROVER", "DISCOVERY SPORT", 7, ["DISC SPT", "DISCOVERY SPORT"]],
  ["LAND ROVER", "DEFENDER", 7],
  ["LAND ROVER", "DISCOVERY", 7],
  ["LAND ROVER", "FREELANDER", 7],
  ["LAND ROVER", "FREELANDER 2", 7, ["FREELANDER2", "FREELANDER 2"]],
  // Other car makes
  ["JAC", "J2", 2],
  ["JAC", "J3", 2],
  ["JAC", "J6", 7],
  ["TROLLER", "T4", 7],
  ["GEELY", "EX2", 2],
  ["GEELY", "EX5", 7],
  ["OMODA", "5", 7],
  ["JAECOO", "7", 7],
  ["PORSCHE", "CAYENNE", 7],
  ["PORSCHE", "MACAN", 7],
  ["PORSCHE", "911", 2],
  ["MINI", "COOPER", 2],
  ["DODGE", "JOURNEY", 7],
  ["DODGE", "DAKOTA", 3],
  ["IVECO", "DAILY", 3],
  ["LIFAN", "X60", 7],
  ["SUBARU", "FORESTER", 7],
  ["SUBARU", "IMPREZA", 2],
  ["MARCOPOLO", "VOLARE", 5],
  // Other motorcycle makes
  ["KAWASAKI", "NINJA", 1],
  ["KAWASAKI", "VERSYS", 1],
  ["KAWASAKI", "VERSYS-X", 1],
  ["KAWASAKI", "Z900", 1],
  ["KAWASAKI", "VULCAN", 1],
  ["KAWASAKI", "ER-6N", 1],
  ["TRIUMPH", "TIGER", 1],
  ["TRIUMPH", "SCRAMBLER", 1],
  ["TRIUMPH", "SPEED", 1],
  ["TRIUMPH", "STREET TRIPLE", 1],
  ["TRIUMPH", "BONNEVILLE", 1],
  ["ROYAL ENFIELD", "HIMALAYAN", 1, ["HIMALAYAN", "HIMALAYA"]],
  ["ROYAL ENFIELD", "METEOR", 1],
  ["ROYAL ENFIELD", "SUPER METEOR", 1],
  ["ROYAL ENFIELD", "HUNTER", 1, ["ROYAL HUNTER"]],
  ["ROYAL ENFIELD", "CLASSIC", 1],
  ["ROYAL ENFIELD", "INTERCEPTOR", 1, ["INT 650", "INT BEAR"]],
  ["ROYAL ENFIELD", "GUERRILLA", 1],
  ["ROYAL ENFIELD", "SCRAM", 1],
  ["ROYAL ENFIELD", "CONTINENTAL GT", 1, ["CGT"]],
  ["ROYAL ENFIELD", "SHOTGUN", 1],
  ["BAJAJ", "DOMINAR", 1],
  ["BAJAJ", "PULSAR", 1],
  ["DAFRA", "SPEED", 1],
  ["DAFRA", "ZIG", 1],
  ["DAFRA", "KANSAS", 1],
  ["DAFRA", "SUPER", 1],
  ["DAFRA", "CITYCOM", 1],
  ["DAFRA", "RIVA", 1],
  ["DAFRA", "NEXT", 1],
  ["SUNDOWN", "WEB", 1],
  ["SUNDOWN", "MAX", 1],
  ["SUNDOWN", "HUNTER", 1],
  ["SUNDOWN", "STX", 1],
  ["SUNDOWN", "FUTURE", 1],
  ["KASINSKI", "COMET", 1],
  ["KASINSKI", "MIRAGE", 1],
  ["SHINERAY", "SHI", 1],
  ["MOTTU", "SPORT", 1],
];
